"use client"

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import {useState,useEffect } from 'react';
import NavBar from './components/NavBar';
import Sidebar from './components/Sidebar';


export default function RootLayout({ children }) {

  const [showNavBar, setShowNavBar] = useState(false);
  const [login, setLogin] = useState(true);
  const [showSidebar, setShowSidebar] = useState(true);
  const [authenticated, setAuthenticated] = useState(true);

    
const toggleSidebar = () => {
  setShowSidebar(!showSidebar);
}

function isMobile() {
  const screenWidth = window.innerWidth;
  return screenWidth < 768;
}

useEffect(() => {
  const timeoutId = setTimeout(() => {
    setShowNavBar(true);

    if (isMobile()) {
      setShowSidebar(!setShowSidebar);
    }
  });
  return () => clearTimeout(timeoutId);
}, []);
  return (
    <html lang="en">
      <body className={inter.className}>
     
      <div >
          {showNavBar && <NavBar toggleSidebar={toggleSidebar} showSidebar={showSidebar} />}
            <div className="flex">
            {showSidebar && <Sidebar toggleSidebar={toggleSidebar} showSidebar={showSidebar} />}
              <main className="flex-grow">

              {children}
            
        </main>
      </div>
    </div>
   </body>
    </html>
  )
}
